# Generated by Django 2.2 on 2019-11-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191116_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otziv',
            name='ocenka',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Оценка'),
        ),
    ]
