# Generated by Django 2.2 on 2019-11-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191116_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otziv',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_otziv', to='webapp.Product', verbose_name='Товар'),
        ),
    ]
